// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
