// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ECooldown():Promise<string>;

export function Error():Promise<string>;

export function IsRunning():Promise<boolean>;

export function LCooldown():Promise<string>;

export function Log():Promise<Array<Record<string, string>>>;

export function RCooldown():Promise<string>;

export function StartAutoKey():Promise<void>;

export function StartAutoKeyNetwork():Promise<void>;

export function StartBot():Promise<void>;

export function Stop():Promise<void>;

export function TimeStr():Promise<string>;
