// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Error() {
  return window['go']['main']['App']['Error']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function StartAutoKey() {
  return window['go']['main']['App']['StartAutoKey']();
}

export function StartBot() {
  return window['go']['main']['App']['StartBot']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TimeStr() {
  return window['go']['main']['App']['TimeStr']();
}
